version: '3'
services:
  db:
    image: mongo:6.0.6
    container_name: db_cidadao
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mongoadmin'
      MONGO_INITDB_ROOT_PASSWORD: 'secret'
    networks:
      - dev-cidadao

  source:
    build: .
    container_name: src_cidadao
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes: 
      - ..:/workspace/source
    networks:
      - dev-cidadao

networks:
  dev-cidadao:
    driver: bridge
